#!/usr/bin/perl

### BEGIN INIT INFO
# Provides:          pokemononline
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: PokemonOnline service 1.0
# Description:       PokemonOnline service 1.0
# Documentation:     https://synchronetbbs.org/index.php/forum/alternate-startup-scripts
# Type:              forking
# X-Interactive:     false
### END INIT INFO

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

my $POKEMONONLINEDIR = "/root/pokemon-online";

my $Command = $ARGV[0];
if ($Command eq "")
{
	$Command = "NONE";
}

my $running=`ps ax|grep "./Server --headless"|grep -v grep`;

if ($Command eq "start")
{
	if ($running eq "")
	{
		print "Starting Pokemon Online...\n";
		if (-f "$POKEMONONLINEDIR/nostart")
		{
			print "Removing $POKEMONONLINEDIR/nostart\n";
			# Remove the lock file if it exists
			unlink("$POKEMONONLINEDIR/nostart");
		}
		# Start the screen process
		system("nohup $POKEMONONLINEDIR/startminetest > /tmp/PokemonOnlineStartup.log\&");
	}
}
elsif ($Command eq "stop")
{
	print "Stopping Pokemon Online process...\n";
	system("touch '$POKEMONONLINEDIR/nostart'");
	if ($running ne "")
	{
		# Process is running, kill it
		system("killall \"./Server --headless\"");
	}
}
elsif ($Command eq "restart")
{
	if (-f "$POKEMONONLINEDIR/nostart")
	{
		print("Removing $POKEMONONLINEDIR/nostart\n");
		unlink("$POKEMONONLINEDIR/nostart");
	}
	if ($running ne "")
	{
		system("killall \"./Server --headless\"");
	}
}
elsif ($Command eq "status")
{
	if ($running ne "")
	{
		print("Pokemon Online Server Running\n");
	}
	else
	{
		print("Pokemon Online Server Not Running\n");
	}
}
else
{
	print ("Uknown command '$Command'\n");
	print ("Usage: $0 {start|status|stop|restart}\n");
	exit(1);
}

exit(0);
