#!/usr/bin/perl

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

my $POKEMONONLINEDIR = "/root/pokemon-online";
my $SCREENCMD = "/usr/bin/screen";

# No changes below here...

my $startpath = $ENV{'PATH'};
my $newpath = "$POKEMONONLINEDIR/bin:$startpath";
my $exists = "";

# Set ENV vars
$ENV{'PATH'} = $newpath;
$ENV{'TERM'} = "xterm-256color";

my $running=`ps ax|grep "./Server --headless"|grep -v grep`;

# check if Pokemon Online server process is running
if ($running ne "")
{
	print ("Startupscript already running...\n");
	exit (0);
}

while (-1)
{
	chdir $POKEMONONLINEDIR;
	# check if Pokemon Online server process is running
	$running=`ps ax|grep "./Server --headless"|grep -v grep`;
	if ($running eq "")
	{
		print "Pokemon Online server not running\n";
		# See if they want the server started
		if (! -f "$POKEMONONLINEDIR/nostart")
		{
			# The Log Entry
			my $datestring = localtime();
			my $TIME="Pokemon Online server Down, Restarting: $datestring";
			open(OUTF, ">>$POKEMONONLINEDIR/PokemonOnlineScreen.log") || die "Unable to open $POKEMONONLINEDIR/PokemonOnlineScreen.log for appending";
			print (OUTF "$TIME\n");
			close($OUTF);
			chdir "$POKEMONONLINEDIR/bin";
			print "Starting screen process\n";
			system("$SCREENCMD -fa -S PokemonOnline -d -U -m $POKEMONONLINEDIR/bin/start-server --headless");
		}
	}
	# Sleep for 5 minutes before checking again
	sleep(300);
}
exit(0);
